apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "clmforge.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
        - name: clmforge
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 8765
          env:
            - name: CLM_TOKEN
              value: {{ .Values.env.CLM_TOKEN | quote }}
